<a href="https://colab.research.google.com/github/baebsae3123/BDA/blob/main/3%EC%9D%BC%EC%B0%A8%20%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # 3주차 빅데이터 시간


# 내장함수 array()

In [ ]:
import numpy as np

a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape) #각차원 크기
print(a.ndim) #배열 차원의수
print(a.dtype) # 배열 타입

(3,)
1
int64


In [ ]:
print(a.size) #배열크기
print(a.itemsize) #배열의 타입 정수
print(a.nbytes) #

3
8
24


# 문자열 자료형
array 는 그대로 출력함
ndarray 는 최소화 해서 출력



In [ ]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np.array(['가나다','라마바','사이자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사이자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라마바','사이자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사이자'], dtype='<U32')

# numpy.arange()

In [ ]:
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
print(np.arange(2.0))
print(np.arange(2.0,6.5))
print(np.arange(2.0,6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

배열의 모양을 바꾸는 reshpae()

In [ ]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a,(3,5)) # arrange에 12개 인데 15개라 틀림

ValueError: cannot reshape array of size 12 into shape (3,5)

# linespace

In [ ]:
np.linspace(2.0,3.0)

In [ ]:
np.linspace(2.0,3.0,retstep=True)

In [ ]:
print((3-2)/(50-1))

In [ ]:
np.linspace(2.0,3.0, endpoint=False,retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [ ]:
print((3-2)/50)

In [ ]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [ ]:
np.linspace(2.0,3.0,num=5,endpoint=False,retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

# 내장함수 np.zeros()

In [ ]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

# 원소가 모두 1.0인 배열을 생성하는 ones()

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

# numpy.eve()

In [ ]:
np.eye(3)

In [ ]:
np.eye(2,dtype=True)


In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

#numpy.full

In [ ]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2,3],[1,2,3])

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([2,3],(1,2)) #fill value가 없어서 발생

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [ ]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4,3],fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

#numpy.empty

In [ ]:
np.empty(3)

In [ ]:
np.empty([2,2])

In [ ]:
np.empty([2,3],dtype=int)

In [ ]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#numpy zeros_like()

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#numpy ones_like()

In [ ]:
np.ones_like(a)

#numpy full_likes()

In [ ]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

# 배열과 스칼라와의 연산

In [ ]:
a = np.arange(3)
a

In [ ]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)


# 배열과 배열의 연산

In [ ]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


# 복합 대입 연산자도 지원

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b =np.aranage(0.5,4,1)
b

AttributeError: module 'numpy' has no attribute 'aranage'

In [ ]:
a +=b


In [ ]:
b+= a
b

array([[2, 4, 6],
       [5, 7, 9]])

# 다양한 배열의 곱 연산자

In [ ]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 6)

In [ ]:
a.dot(b)

ValueError: shapes (5,6) and (3,2,2) not aligned: 6 (dim 1) != 2 (dim 1)

In [ ]:
a.dot(a)

In [ ]:
print(np.matmul(a,b))
print(np.matmul(b,a))

# 배열함수

In [ ]:
a = np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum()


np.int64(46)

In [ ]:
a.sum(axis=0)

array([16, 30])

In [ ]:
a.sum(axis=1)

array([30, 13,  3])

In [ ]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

#배열함수

In [ ]:
a = np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
a.cumsum(axis=0)

In [ ]:
a.cumsum(axis=1)

# 다양한 이항연산 범용함수

In [ ]:
a = np.array([1,4,9])
a

array([1, 4, 9])

In [ ]:
b=np.full_like(a,2)

In [ ]:
np.add(a,b)

array([ 3,  6, 11])

In [ ]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [ ]:
np.power(a,b)

array([ 1, 16, 81])

# 1차원 배열의 첨자와 슬라이싱


In [ ]:
a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])


[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


# 역순과 대입

In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[::-2]

array([81, 49, 25,  9,  1])

In [ ]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a[2:5] = [-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [ ]:
a[2:5] = [-5,-5] #대입될 원소수가 3개여야함
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [ ]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

# 2차원 배열의 첨자와 슬라이싱

In [ ]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
a[-2,:]

array([18, 19, 20, 21, 22, 23])

#2차원 배열의 첨자와 슬라이싱

In [ ]:
a[2:4]


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [ ]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [ ]:
a[:,1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

#2차원 배열의 첨자와 슬라이싱

In [ ]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a[:-1,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

#3차원배열의 다양함 참조

```
# 코드로 형식 지정됨
```



In [ ]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:,1,1]

array([ 5, 17])

In [ ]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

# 선생님이랑 한거

In [ ]:
a[-1]
a[-2,:]
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:,1,1]

array([ 5, 17])

In [ ]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

3차원 배열의 다양한 참조


In [ ]:
a[...,1]

In [ ]:
a[1, ...,1]

In [ ]:
a[0,...]


In [ ]:
a[0]

# 3차원 배열의 다양한 참조

In [ ]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[1, ... ,1]

array([13, 17, 21])

In [ ]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 1차원 배열로 만드는 ndarray.revel()

In [ ]:
a = np.arrange(12).reshape(2,3,2)
a

In [ ]:
b = a.ravel()
b

# np.transpose(a) 와 a.transpose(), a.T

In [ ]:
a = np.arange(1,7).reshape(2,3)

In [ ]:
a = np.transpose(a)

In [ ]:
a = transpose()

In [ ]:
a.T

# 3차원 배열의 전치 정렬 (시험 안나옴)

In [ ]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

# 두번쨰 인자로 조정하는 3차원의 전치 행렬

In [ ]:
np.transpose(b,(0,1,2))

In [ ]:
np.transpose(b,(2,1,0))

In [ ]:
np.transpose(b,(0,2,1))

# np.swapaxes(a,axis1,axis2)

In [ ]:
x = np.array([[7,8,9]])

In [ ]:
y = np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [ ]:
y = np.swapaxes(x,1,0)
y

array([[7],
       [8],
       [9]])

In [ ]:
y[0,0] = 10
x

array([[10,  8,  9]])

# 3ㅏㅊ원 배열에서 swapaxes()

In [ ]:
x = np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
np.transpose(x,(2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

2차원 배열의 첨자와 슬라이싱


In [ ]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:,::2]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [20, 21, 22, 23]]])

In [ ]:
a[2,4]

np.int64(16)

In [ ]:
a[2][4]


np.int64(16)

In [ ]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [ ]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a[:-1,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

# 1차원 배열 색인

In [ ]:
x = np.arange(10)
x

In [ ]:
print(x[1])


In [ ]:
print(x[:5])


In [ ]:
print(x[[2]])

In [ ]:
print(x[[2,3]])

In [ ]:
x[[2,3,5,8]]

In [ ]:
x[np.array([5,3,-4,8])]

# 2차원 배열의 색인

In [ ]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x [ [5,6] ]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[ [0,1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[ [0],[1] ]

array([1])

In [ ]:
x[ [0,1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[:,[1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[:,[1,2]]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [ ]:
x[:,[2,1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[[1],[2]]

array([10])

# 행과 열 참조 매핑

In [ ]:
from numpy import arange

x = arange(56).reshape(7 ,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [ ]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [ ]:
x[array([0,2,4]), :2]

NameError: name 'array' is not defined

# 기본 색인 방법

In [ ]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

# 고급 색인방법

In [ ]:
a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[arange(2,5)][:, arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [ ]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[arange(2,5)][:,arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])