<a href="https://colab.research.google.com/github/baebsae3123/BDA/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B04%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy.vstak


In [6]:
import numpy as np

a= np.arange(6).reshape(3,2)
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
np.vstack((a,b))


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
import numpy as np

x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

# hstack 수평으로 결합

In [8]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [10]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

#cloumm_stack


In [11]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack(x[:, np.newaxis], y[:,np.newaxis])


In [12]:
x[: , np.newaxis]

array([[1],
       [2],
       [3]])

In [16]:
np.hstack((x,y))


array([ 1,  2,  3, 10, 20, 30])

In [14]:
np.column_stack == np.hstack

False

In [17]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [22]:
np.row_stack((a,b))

/tmp/ipykernel_12023/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

# concatentate


In [24]:
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [25]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [26]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [27]:
np.concatenate((a,b,c,), axis=None)

array([1, 2, 3, 4, 5, 6])

# numpy.concatenate() 2차원 배열 결합

In [28]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [30]:
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

# numpyy.concatnate() 2차원 배열 결합 axis=1

In [31]:
np.concatenate((x,y),axis=1)


array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [32]:
np.concatenate((x,y,z),axis=1)


array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [33]:
np.concatenate((x,y),axis=None)


array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

#np.stack((arr_1,arr2_) axis=0/1/2

In [54]:
 a = np.array([1,2,3])
 a


array([1, 2, 3])

In [53]:
 b =np.array([4,5,6])
 b

array([4, 5, 6])

In [55]:
np.stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a,b),axis=-1) # -1 와 1은 동일

# np.stack((arr1_arr2),axis=0))

1.   항목 추가
2.   항목 추가



In [43]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [46]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [47]:
ax0 = np.stack((x,y,z ), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

# np.stack((arr1_arr2),axis=0/1/2)


In [56]:
print('np.stack((x,y,z),axis=0)')
print(np.stack((x,y,z),axis=0))
print('np.stack((x,y,z),axis=1)')
print(np.stack((x,y,z),axis=1))
print('np.stack((x,y,z),axis=2)')
print(np.stack((x,y,z),axis=2))

np.stack((x,y,z),axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x,y,z),axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x,y,z),axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


# 연산 np.satck((x,y,z) axis =2) 과정

In [59]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [61]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [63]:
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [65]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [64]:
z[:,:,np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [69]:
np.expand_dims(x,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [70]:
np.expand_dims(y,axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [71]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

# column_satck _ hstack ()

# row_satck()과 vstack()

In [83]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [85]:
np.row_stack((a,b))


/tmp/ipykernel_12023/3896504955.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [86]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# np.coulmn.stack()

In [87]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [89]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# np.column_stack()

In [92]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [93]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [95]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [97]:
np.c_[x, 10, 20,y]


array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [94]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

# np_r

In [98]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [99]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [100]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [101]:
np.row_stack((a,b))

/tmp/ipykernel_12023/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [103]:
np.r_[3:10:3,[0] *2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [102]:
np.r_[-1:1:6j, [0] *2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [105]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [107]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [108]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

# 4-2 배열 분리

In [109]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [110]:
s = np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

# np.split()

In [114]:
y = np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [115]:
np.split(y,[2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

#np.split(ary n axis=1) # hsplit

In [116]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [117]:
np.split(a,3,axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [118]:
np.split(a,4,axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

np.split(axis=0)

In [120]:
b =np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [123]:
np.split(b,[2,4,6],axis =0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

#54

In [124]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [125]:
np.split(a,[3,5,7],axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [126]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [127]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
a = np

In [129]:
rg = np.random.default_rng(12)
r = rg.random()
r

0.2508244581084461

In [130]:
rg.random((3,4))

array([[0.94675294, 0.18932038, 0.17929141, 0.34988924],
       [0.23054125, 0.67044574, 0.11507938, 0.89630937],
       [0.85813049, 0.00282703, 0.54146616, 0.10685127]])

In [131]:
rg.random(5)

array([0.25795496, 0.41689604, 0.45361612, 0.46814659, 0.9275167 ])

In [132]:
rg = np.random.default_rng(12345)
r = rg.integers(low=0,high=10,size=3)
r

array([6, 2, 7])

In [133]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [134]:
rg =np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [136]:
rg.standard_normal((4,3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])